CREATE TABLE Maszkolt_Ugyfel
(LOGIN NVARCHAR(20) PRIMARY KEY,
EMAIL NVARCHAR(30) MASKED WITH (FUNCTION = 'email()'),
NEV NVARCHAR(20) MASKED WITH (FUNCTION = 'partial(2,"XX",1)'),
SZULEV INT MASKED WITH (FUNCTION = 'random(1,1000)'),
NEM NVARCHAR(10),
CIM NVARCHAR(50) MASKED WITH (FUNCTION = 'default()')
);

INSERT INTO Maszkolt_Ugyfel
SELECT * FROM Ugyfel


CREATE USER MaskUser2 WITHOUT Login;
GRANT SELECT ON Maszkolt_Ugyfel TO MaskUser2

EXECUTE AS User= 'MaskUser2';
SELECT * FROM Maszkolt_Ugyfel
REVERT
